# Generated by Django 4.2.7 on 2023-11-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_description_and_more'),
        ('core', '0012_alter_productreview_rating'),
    ]

    operations = [
    ]
