# Generated by Django 4.2.7 on 2023-11-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20231123_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=40),
        ),
    ]
